### PR TITLE
Add additional timer metrics. Fix sum and mean metrics

### PR DESCRIPTION
**Pull request by JoseKilo**
Hi,

I was missing some timer stats from the original Etsy's Statsd, like median, standard deviation, etc. So I started to add them. While I was doing that, I also noticed mismatches in some other stats (at least, `mean` and `sum`), related to how Bucky truncates the list of values.

I would like also to include support for different `threshold` levels.

Let me know any thoughts.

Reference: original code in Statsd: https://github.com/etsy/statsd/blob/master/lib/process_metrics.js

### CODE REVIEW

**Comment by trbs** [comment]
sorry for the wait.

thanks for the patch !

**Comment by JoseKilo** [comment]
No worries, thanks for merging :+1:

**Comment by trbs** [comment]
Are you using this code in production ?

**Comment by JoseKilo** [comment]
I have been using the version from pip in a production environment for some time. I have tried the code from this PR in a production-like environment, but with very low traffic / load.
I will probably update all the systems very soon. I will let you know.

If you are familiar with Ansible, this is the ansible role that I'm using to install and configure Bucky https://github.com/rockabox/Scoota.bucky

**Comment by trbs** [comment]
I'm using the pip version in production (20+ machines) as well for a long time now. I am wondering how your changes will impact performance of Bucky... I would love to be able to claim that we are faster then statsd :) (i would not be supprised if bucky on pypy would actually be faster)

I also use ansible a lot and our roles look very much alike, although I use supervisord to manage processes.

If you want please send a PR to update the documentation with a link to your ansible role.

**Pull request merged**
