### PR TITLE
Dogstatsd metadata support

### PR DESCRIPTION
**Pull request by jsiembida**
This is to add support for StatsD protocol extension as used in DatadogStatsD.

http://docs.datadoghq.com/guides/dogstatsd/#datagram-format

### CODE REVIEW

**Comment by trbs** [comment]
Thanks for your work on this !

I am a little worried about the possible performance implications specially in the case where one is not using the metadata support.

Could you do something similar as in `contrib/statsd_perfomance_test.py` so we can measure the impact of your PR ?

**Comment by jsiembida** [comment]
Hi, I just run the performance script:

master branch `('Result:', 14.400677919387817)`
dogstatsd-metadata-support branch `('Result:', 14.200869083404541)`

I made sure that the metadata code breaks as early as possible if there is no metadata on the wire, so hopefully people using the "classic" StatsD protocol should see no performance impact.

**Comment by jsiembida** [comment]
I added more perf tests to see the impact on the parsing codepath:

master branch:
('Result:', 14.287160158157349)
('Result:', 53.849238872528076)

dogstatsd-metadata-support branch:
('Result:', 14.318003177642822)
('Result:', 59.50106692314148)

**Comment by trbs** [comment]
Thanks !

Looking good :)

**Pull request merged**
